### ISSUE TITLE
Degraded performance on v1.9.8 on mobile devices

### ISSUE THREAD

**Issue by chenghong** [stefangabos/Zebra_Datepicker#116]
Tested using v1.9.8 on latest Chrome on Android.

Steps:
1) Open a datepicker by tapping the parent text box
2) Close the datepicker by tapping elsewhere on the page
3) Drag the page a little
4) Repeat

The datepicker will come to a point where it takes a few seconds to open upon tapping on the parent text box. Expectation is that it should open immediately.

Such performance degradation do not happen on v1.9.7.

**Comment by chenghong** [comment]
Here is a reduced test case: https://codepen.io/anon/pen/eKodaM

**Comment by stefangabos** [comment]
i am still unable to reproduce it. maybe also tell me the device you are testing this on? i am using browser stack and i can test a lot of devices. there is a small delay but it is there because it waits for the keyboard to open (which scrolls the screen)

**Comment by chenghong** [comment]
I am using Huawei P20 Pro, Chrome browser. Previously was using Huawei P9 and same issue.

Try tapping the icon area situated roughly right-most of the textbox to open the datepicker. It shouldn't bring up the keyboard as there is no text input expected. Tap anywhere else on the white page the close the datepicker. Then scroll the white page a little. Then try open the datepicker again.

**Comment by stefangabos** [comment]
Luckily my own phone is a P9 but I am unable to reproduce this. There *is* a delay that was introduced in 1.9.8 that is there in order to account for the time it takes for the keyboard to show but it's not getting longer for me even if i tried 20+ times. what i noticed is that if i keep moving (scrolling) the page  around a lot and then quickly tap on where the icon should be, it might take *a bit* longer (like it is waiting for the scrolling to settle) but still the total waiting time is less than a second i think. 

don't get me wrong - i'm not saying that this is not happening, i am just saying that i am unable to reproduce it

**Comment by chenghong** [comment]
Just wondering, did the keyboard appear for you in any of your tests?

I'll try to create a video if possible.

**Comment by stefangabos** [comment]
Yes, the keyboard appeared every time

**Comment by chenghong** [comment]
Here you go: https://www.youtube.com/watch?v=o2gyAa6WoS0

As you can see, no keyboard being activated throughout.
The datepicker only becomes slow to load after the page is dragged around a bit.

**Comment by stefangabos** [comment]
See if this works better, please
https://codepen.io/anon/pen/rKbyNj

**Comment by chenghong** [comment]
It does appear to solve the original problem, but it introduces a new issue - the page now has a very visible flicker, a few seconds after the page is fully loaded.

**Comment by stefangabos** [comment]
It has to be something else as all I did was to remove a call for setTimeout...it has to be from codepen. I'll do a release soon and then you'll be able to test it with the examples from the demo page

**Comment by stefangabos** [comment]
Thank **you** for taking the time to report and helping me test and fix it!
